### ISSUE TITLE
Getting "TypeError: _.upperFirst is not a function" when running "yo jhipster-stormpath"

### ISSUE THREAD

**Issue by apveitas** [stormpath/generator-jhipster-stormpath#17]
Hi,

Am running "yo jhipster-stormpath" and it's failing....here is the console...any tips?

aveitas@aveitas-Gazelle-Pro:~/ideas/$ yo jhipster-stormpath
Composing JHipster configuration with module stormpath

                   `.-::::-.`               
               -/shddddddddddhs/-           
            `+hddddddddddddddhyso+`         
          `+hddddddddhyo/:.`      -s+`      
         -hddddddds/.           -sdddh-     
        -hddddddo`             /ddddddh-    
       `hdddddh-                /hdddddh`   
       +dddddd/      /shhs/      /dddddd/   
       sdddddd`     sdddddds     `dddddds   
       sdddddd`     sdddddds     `dddddds   
       /dddddd/      /shhs/      /dddddd/   
       `hdddddh/                -hdddddh`   
        -hdddddd/             .oddddddh-    
         -hddds-           ./sdddddddh-     
          `+s-      `.:/oyhddddddddh+`      
             `+osyhddddddddddddddh+`        
               -/shddddddddddhs/-           
                   `.-::::-.`               

Welcome to the JHipster Stormpath generator! v0.0.3

Please check your project into Git before you install Stormpath!
That way, you can easily undo this installation using: git checkout .

NOTE: You need to have a Stormpath account for this module to work!
      Register at https://api.stormpath.com/register, generate API keys,
      and copy to ~/.stormpath/apiKey.properties.

Reading the JHipster project configuration for your module
? Do you want to install Stormpath? Yes
TypeError: _.upperFirst is not a function
    at module.exports.yeoman.Base.extend.writing.setupGlobalVar (/home/aveitas/ideas//node_modules/generator-jhipster-stormpath/generators/app/index.js:118:42)
    at Object.<anonymous> (/home/aveitas/ideas//node_modules/generator-jhipster-stormpath/node_modules/yeoman-generator/lib/base.js:436:25)
    at /home/aveitas/ideas//node_modules/generator-jhipster-stormpath/node_modules/run-async/index.js:25:25
    at /home/aveitas/ideas//node_modules/generator-jhipster-stormpath/node_modules/run-async/index.js:24:19
    at /home/aveitas/ideas//node_modules/generator-jhipster-stormpath/node_modules/yeoman-generator/lib/base.js:448:8
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by mraible** [comment]
What version of Yeoman, JHipster and Node are you using? Below is the output on my system:

```
$ yo --version
1.8.5
$ node --version 
v6.9.1
```

**Comment by apveitas** [comment]
Thanks for the quick response!

$ yo --version
1.8.5
$ node --version
v4.4.2

**Comment by apveitas** [comment]
jhipster from package.json

    "generator-jhipster": "3.12.0",

**Comment by mraible** [comment]
Can you try it with Node v4.5.0? I developed the module using that version and haven't tested on v4.4.2.

**Comment by apveitas** [comment]
Having problems installing Node v4.5.0 on my ubuntu machine.

Tried with 5.10.0 and got same issue, fwiw

**Comment by mraible** [comment]
I'm unable to reproduce this with 5.10.0 on a Mac. It seems like this might be caused by [lodash 3.x](https://github.com/donejs/generator-donejs/issues/85). Can you try installing lodash 4.x?

```
npm install lodash
```

**Comment by apveitas** [comment]
package.json at my root level directory for project is 4.0.15

**Comment by mraible** [comment]
What OS and version are you using? 

Can you please post your .yo-rc.json?

**Comment by mraible** [comment]
Can you try to `rm -rf node_modules` and run `npm install` again?

**Comment by ruddell** [comment]
I couldn't reproduce this locally or with the JHipster dev docker image (macOS, Ubuntu 16, LTS node v6.9.1).  I also tried with Ubuntu 14 and node v4.5.0

**Comment by apveitas** [comment]
**RE: What OS and version are you running?**: ubuntu 15.04

**RE: Can you please post your .yo-rc.json?**
``
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.0",
    "baseName": "x",
    "packageName": "com.X",
    "packageFolder": "com/X",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "9233f1be971e6489905789cb3e854c6fdb0ec1e2",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "serviceDiscoveryType": false
  }
}

**Comment by apveitas** [comment]
Still having the same issue.....

As requested, tried m -rf node_modules and run npm install....noluck

Upgraded to Ubuntu 16.04

$ npm -v
4.0.3

$ node -v
v4.5.0

$ vi .yo-rc-global.json
{
  "generator-jhipster:3.12.0": {
    "promptValues": {
      "packageName": "com.x"
    }
  }
}

$ vi .yo-rc.json
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.0",
    "baseName": "x",
    "packageName": "com.X",
    "packageFolder": "com/X",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "3d2ed030671aeae7908be2dac1f66445bd219c52",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}

**Comment by apveitas** [comment]
In addition, here is the log when installing the stormpath generator

$:~/ideas/x$ npm install generator-jhipster-stormpath
x@0.0.0 /home/aveitas/ideas/x
└─┬ generator-jhipster-stormpath@0.0.3 
  ├─┬ mkdirp@0.5.1 
  │ └── minimist@0.0.8 
  └─┬ yeoman-generator@0.22.4 
    ├── async@1.5.2 
    ├─┬ cross-spawn@2.2.3 
    │ └── cross-spawn-async@2.2.5 
    ├── glob@6.0.4 
    ├─┬ inquirer@0.11.4 
    │ └── run-async@0.1.0 
    ├─┬ istextorbinary@1.0.2 
    │ ├── binaryextensions@1.0.1 
    │ └── textextensions@1.0.2 
    ├── lodash@3.10.1 
    ├── pretty-bytes@2.0.1 
    ├── run-async@2.3.0 
    └── shelljs@0.5.3 

**npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})**

**Comment by apveitas** [comment]
Working!  Not sure exactly why but I may have specified -g when installing the generator

**Comment by ckushwaha207** [comment]
Hello folks,

I am getting this issue for generator-jhipster:4.0.6. Can someone help me to fix this issue ?

**Comment by mraible** [comment]
This library has not been updated for JHipster 4.x. I started working on upgrading it yesterday.
